import js from "@eslint/js";
import globals from "globals";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  { ignores: ["node_modules/**"] },
  js.configs.recommended,
  {
    // Los archivos de js/ se cargan como scripts clásicos (sin módulos ni build step)
    // y comparten un único scope global en el navegador, tal como en el index.html
    // original de un solo archivo. Cada función/constante de nivel superior es en la
    // práctica una "exportación" usada por otros archivos, así que:
    // - se declaran aquí como globals compartidos para que no-undef no marque falsos positivos
    // - no-unused-vars solo revisa variables locales (dentro de funciones), no las de nivel superior
    files: ["js/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        ...globals.browser,
        // config de la copia en la nube (js/supabase-config.js)
        SUPABASE_URL: "readonly",
        SUPABASE_ANON_KEY: "readonly",
        // compartidos entre archivos (solo lectura)
        $: "readonly",
        cloudConfigured: "readonly",
        renderCloud: "readonly",
        handleAuthRedirect: "readonly",
        cloudInit: "readonly",
        queueCloudSync: "readonly",
        validateImportedState: "readonly",
        DEFAULT_CATEGORIES: "readonly",
        CAT_COLOR: "readonly",
        catColor: "readonly",
        PRIOS: "readonly",
        REPEATS: "readonly",
        THEMES: "readonly",
        WCODE: "readonly",
        curMonth: "readonly",
        defaultState: "readonly",
        esc: "readonly",
        flashNew: "readonly",
        exportBackup: "readonly",
        checkBackupReminder: "readonly",
        checkTaskReminders: "readonly",
        notify: "readonly",
        VIEWS: "readonly",
        fetchedMonths: "readonly",
        fetchHistoryForMonth: "readonly",
        initValues: "readonly",
        loadWeather: "readonly",
        money: "readonly",
        moneyShort: "readonly",
        pad: "readonly",
        renderAll: "readonly",
        renderBalance: "readonly",
        renderCalendar: "readonly",
        renderCatSelects: "readonly",
        renderCategories: "readonly",
        renderCategoryBudgets: "readonly",
        renderFixedIncomes: "readonly",
        rolloverFixedIncomes: "readonly",
        renderChrome: "readonly",
        renderConfig: "readonly",
        renderFinance: "readonly",
        renderFixedExpenses: "readonly",
        renderFocus: "readonly",
        renderGoals: "readonly",
        renderHabits: "readonly",
        renderHealth: "readonly",
        renderLock: "readonly",
        selectedMonth: "readonly",
        openAddSheet: "readonly",
        renderHome: "readonly",
        renderMonthlySummary: "readonly",
        renderRoutines: "readonly",
        renderTasks: "readonly",
        rolloverTasks: "readonly",
        rolloverFixedExpenses: "readonly",
        startEditTx: "readonly",
        startEditTask: "readonly",
        save: "readonly",
        shiftMonth: "readonly",
        streakOf: "readonly",
        switchView: "readonly",
        toast: "readonly",
        todayStr: "readonly",
        uid: "readonly",
        ymd: "readonly",
        // compartidos entre archivos (reasignados)
        state: "writable",
        stateLoadError: "writable",
        calMonth: "writable",
        finSearch: "writable",
        finFilterCat: "writable",
        finFilterType: "writable",
        editingTx: "writable",
        editingTask: "writable",
      },
    },
    rules: {
      "no-unused-vars": ["error", { vars: "local" }],
      // cada global de la lista de arriba se declara "de verdad" (function/const) en
      // exactamente uno de estos archivos; eso es la declaración real, no una redeclaración
      "no-redeclare": "off",
    },
  },
  {
    files: ["sw.js"],
    languageOptions: {
      sourceType: "script",
      globals: globals.serviceworker,
    },
  },
  {
    // Infra de pruebas en Node (CommonJS).
    files: ["tests/serve.js", "playwright.config.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: globals.node,
    },
  },
  {
    // Specs de Playwright: corren en Node, pero sus callbacks de page.evaluate
    // referencian los globals del navegador y de la app.
    files: ["tests/**/*.spec.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        ...globals.browser,
        state: "writable",
        save: "readonly",
        todayStr: "readonly",
        curMonth: "readonly",
        defaultState: "readonly",
        renderAll: "readonly",
        renderFinance: "readonly",
        renderHabits: "readonly",
        switchView: "readonly",
        rolloverTasks: "readonly",
        rolloverFixedExpenses: "readonly",
        checkTaskReminders: "readonly",
        validateImportedState: "readonly",
        encryptState: "readonly",
        decryptState: "readonly",
        cloudUpload: "readonly",
        cloudDownload: "readonly",
        cloudPull: "readonly",
        setAutoSync: "readonly",
        cloudSyncDelay: "writable",
        buildMonthlyReport: "readonly",
        financialHealth: "readonly",
        parseCSV: "readonly",
        detectColumns: "readonly",
        parseCsvAmount: "readonly",
        parseCsvDate: "readonly",
        buildCsvItems: "readonly",
        openCsvModal: "readonly",
        setPin: "readonly",
        verifyPin: "readonly",
        pinConfigured: "readonly",
        clearPin: "readonly",
        showLock: "readonly",
        $: "readonly",
      },
    },
  },
  {
    files: ["eslint.config.mjs"],
    languageOptions: {
      sourceType: "module",
      globals: globals.node,
    },
  },
  eslintConfigPrettier,
];
